service: atmus-assist

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1
  stackName: atmus-assist-stack
  apiName: py-atmus-assist-api
  deploymentBucket:
    name: ${self:provider.apiName}
  memorySize: 3008
  timeout: 300
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListObjects"
        - "s3:ListBucket"
      Resource:
        Fn::GetAtt:
          - ModelBucket
          - Arn
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:HeadObject"
        - "s3:PutObject*"
      Resource:
        - Fn::Join:
            - ""
            - - Fn::GetAtt:
                  - ModelBucket
                  - Arn
              - /*

plugins:
  - serverless-python-requirements

package:
  exclude:
    - node_modules/**
    - .aws-sam/**
    - .git/**
    - .idea/**
    - .serverless/**
    - .vscode/**
    - __pycache__/**
    - src/__pycache__/**

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    zip: true

functions:
  botHandler:
    handler: src/intent_processor.handler
    events:
      - http:
          path: processIntent
          method: post
    environment:
      MODEL_BUCKET_NAME:
        Ref: ModelBucket
  botTrainer:
    handler: src/trainer.handler
    events:
      - http:
          path: train
          method: post
    environment:
      MODEL_BUCKET_NAME:
        Ref: ModelBucket

resources:
  Resources:
    ModelBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ras-model-bot